# docker exec -it localsql bash 
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
    #   - pgdata:/var/lib/postgresql/data 
# volumes:
#   pgdata: