# docker exec -it localsql bash 
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=rootdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata: